on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main
    with:
      clippy_default: false
      clippy_args: '-- -A clippy::derive_hash_xor_eq'

  test_nightly_std:
    name: Nightly tests std
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --all-features

  test_nightly_no_std:
    name: Nightly tests no_std
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --no-default-features
